// Mocks generated by Mockito 5.3.2 from annotations
// in tv/test/helpers/test_helper_tv.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i18;
import 'dart:typed_data' as _i19;

import 'package:core/core.dart' as _i9;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/io_client.dart' as _i5;
import 'package:http/src/base_request.dart' as _i17;
import 'package:http/src/response.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie/movie.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i15;
import 'package:tv/data/models/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_model.dart' as _i13;
import 'package:tv/data/models/tv_season_detail_model.dart' as _i4;
import 'package:tv/data/models/tv_table.dart' as _i14;
import 'package:tv/domain/entities/tv.dart' as _i10;
import 'package:tv/domain/entities/tv_detail.dart' as _i11;
import 'package:tv/domain/entities/tv_season_detail.dart' as _i12;
import 'package:tv/tv.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTVDetailResponse_1 extends _i1.SmartFake
    implements _i3.TVDetailResponse {
  _FakeTVDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTVSeasonDetailModel_2 extends _i1.SmartFake
    implements _i4.TVSeasonDetailModel {
  _FakeTVSeasonDetailModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOStreamedResponse_3 extends _i1.SmartFake
    implements _i5.IOStreamedResponse {
  _FakeIOStreamedResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TVRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRepository extends _i1.Mock implements _i7.TVRepository {
  MockTVRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> getAiringTodayTVs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiringTodayTVs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #getAiringTodayTVs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> getOnTheAirTVs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTVs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #getOnTheAirTVs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> getPopularTVs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTVs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #getPopularTVs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> getTopRatedTVs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTVs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #getTopRatedTVs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i11.TVDetail>> getTVDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTVDetail,
          [id],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, _i11.TVDetail>>.value(
            _FakeEither_0<_i9.Failure, _i11.TVDetail>(
          this,
          Invocation.method(
            #getTVDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i11.TVDetail>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> getTVRecommendations(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTVRecommendations,
          [id],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #getTVRecommendations,
            [id],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> searchTVs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTVs,
          [query],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #searchTVs,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, _i12.TVSeasonDetail>> getSeasonDetailTV(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetailTV,
          [
            id,
            seasonNumber,
          ],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i12.TVSeasonDetail>>.value(
                _FakeEither_0<_i9.Failure, _i12.TVSeasonDetail>(
          this,
          Invocation.method(
            #getSeasonDetailTV,
            [
              id,
              seasonNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i12.TVSeasonDetail>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> saveWatchlist(
          _i11.TVDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
            _FakeEither_0<_i9.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [tv],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, String>> removeWatchlist(
          _i11.TVDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, String>>.value(
            _FakeEither_0<_i9.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tv],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, String>>);
  @override
  _i8.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>> getWatchlistTVs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTVs,
          [],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.TV>>(
          this,
          Invocation.method(
            #getWatchlistTVs,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.TV>>>);
}

/// A class which mocks [TVRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVRemoteDataSource extends _i1.Mock
    implements _i7.TVRemoteDataSource {
  MockTVRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i13.TVModel>> getAiringTodayTVs() => (super.noSuchMethod(
        Invocation.method(
          #getAiringTodayTVs,
          [],
        ),
        returnValue: _i8.Future<List<_i13.TVModel>>.value(<_i13.TVModel>[]),
      ) as _i8.Future<List<_i13.TVModel>>);
  @override
  _i8.Future<List<_i13.TVModel>> getOnTheAirTVs() => (super.noSuchMethod(
        Invocation.method(
          #getOnTheAirTVs,
          [],
        ),
        returnValue: _i8.Future<List<_i13.TVModel>>.value(<_i13.TVModel>[]),
      ) as _i8.Future<List<_i13.TVModel>>);
  @override
  _i8.Future<List<_i13.TVModel>> getPopularTVs() => (super.noSuchMethod(
        Invocation.method(
          #getPopularTVs,
          [],
        ),
        returnValue: _i8.Future<List<_i13.TVModel>>.value(<_i13.TVModel>[]),
      ) as _i8.Future<List<_i13.TVModel>>);
  @override
  _i8.Future<List<_i13.TVModel>> getTopRatedTVs() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTVs,
          [],
        ),
        returnValue: _i8.Future<List<_i13.TVModel>>.value(<_i13.TVModel>[]),
      ) as _i8.Future<List<_i13.TVModel>>);
  @override
  _i8.Future<_i3.TVDetailResponse> getTVDetail(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTVDetail,
          [id],
        ),
        returnValue:
            _i8.Future<_i3.TVDetailResponse>.value(_FakeTVDetailResponse_1(
          this,
          Invocation.method(
            #getTVDetail,
            [id],
          ),
        )),
      ) as _i8.Future<_i3.TVDetailResponse>);
  @override
  _i8.Future<List<_i13.TVModel>> getTVRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTVRecommendations,
          [id],
        ),
        returnValue: _i8.Future<List<_i13.TVModel>>.value(<_i13.TVModel>[]),
      ) as _i8.Future<List<_i13.TVModel>>);
  @override
  _i8.Future<List<_i13.TVModel>> searchTVs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTVs,
          [query],
        ),
        returnValue: _i8.Future<List<_i13.TVModel>>.value(<_i13.TVModel>[]),
      ) as _i8.Future<List<_i13.TVModel>>);
  @override
  _i8.Future<_i4.TVSeasonDetailModel> getSeasonDetailTV(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetailTV,
          [
            id,
            seasonNumber,
          ],
        ),
        returnValue: _i8.Future<_i4.TVSeasonDetailModel>.value(
            _FakeTVSeasonDetailModel_2(
          this,
          Invocation.method(
            #getSeasonDetailTV,
            [
              id,
              seasonNumber,
            ],
          ),
        )),
      ) as _i8.Future<_i4.TVSeasonDetailModel>);
}

/// A class which mocks [TVLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVLocalDataSource extends _i1.Mock implements _i7.TVLocalDataSource {
  MockTVLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> insertWatchlist(_i14.TVTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  _i8.Future<String> removeWatchlist(_i14.TVTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tv],
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  _i8.Future<_i14.TVTable?> getTVById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTVById,
          [id],
        ),
        returnValue: _i8.Future<_i14.TVTable?>.value(),
      ) as _i8.Future<_i14.TVTable?>);
  @override
  _i8.Future<List<_i14.TVTable>> getWatchlistTVs() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTVs,
          [],
        ),
        returnValue: _i8.Future<List<_i14.TVTable>>.value(<_i14.TVTable>[]),
      ) as _i8.Future<List<_i14.TVTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i9.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i15.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i8.Future<_i15.Database?>.value(),
      ) as _i8.Future<_i15.Database?>);
  @override
  _i8.Future<int> insertWatchlistMovie(_i16.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlistMovie,
          [movie],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
  @override
  _i8.Future<int> insertWatchListTV(_i14.TVTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #insertWatchListTV,
          [tv],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
  @override
  _i8.Future<int> removeWatchlistMovie(_i16.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistMovie,
          [movie],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
  @override
  _i8.Future<int> removeWatchlistTV(_i14.TVTable? tv) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlistTV,
          [tv],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
  @override
  _i8.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<Map<String, dynamic>?> getTVById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTVById,
          [id],
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);
  @override
  _i8.Future<List<Map<String, dynamic>>> getWatchlistTVs() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTVs,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [IOClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.IOClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.IOStreamedResponse> send(_i17.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i8.Future<_i5.IOStreamedResponse>.value(_FakeIOStreamedResponse_3(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i8.Future<_i5.IOStreamedResponse>);
  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i8.Future<_i6.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i18.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i18.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i18.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i18.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i6.Response>.value(_FakeResponse_4(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response>);
  @override
  _i8.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<String>.value(''),
      ) as _i8.Future<String>);
  @override
  _i8.Future<_i19.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i19.Uint8List>.value(_i19.Uint8List(0)),
      ) as _i8.Future<_i19.Uint8List>);
}
