// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHkZYIfLpkjJhUPEz3_bODxd1lZ9vmltg',
    appId: '1:179351215410:web:763959909b633633decb2b',
    messagingSenderId: '179351215410',
    projectId: 'ditonton-5b8b6',
    authDomain: 'ditonton-5b8b6.firebaseapp.com',
    storageBucket: 'ditonton-5b8b6.appspot.com',
    measurementId: 'G-17QHKK1GK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqAS3zXAN0suj1ckxsrhqOWKpW8VQyPEs',
    appId: '1:179351215410:android:5c6df74ce6db3d92decb2b',
    messagingSenderId: '179351215410',
    projectId: 'ditonton-5b8b6',
    storageBucket: 'ditonton-5b8b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7LHSBCKK3OqF-rxzoElw0BYdAk8cTo4',
    appId: '1:179351215410:ios:73d4bcc3e5142b23decb2b',
    messagingSenderId: '179351215410',
    projectId: 'ditonton-5b8b6',
    storageBucket: 'ditonton-5b8b6.appspot.com',
    iosClientId: '179351215410-utbjkfc6m35okfvjeq3lvna43tufjds6.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
